# Generated by Django 5.0.2 on 2024-02-26 18:56

import autoslug.fields
import django.core.validators
import re
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MaxLengthValidator(limit_value=100, message='Slug is over 100 letters long!')], verbose_name='Title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Post content')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, max_length=100, null=True, populate_from='title', unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid'), django.core.validators.MaxLengthValidator(limit_value=100, message='Slug is over 100 letters long!')])),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=10, null=True, verbose_name='Post Status')),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='posts', verbose_name='Post image')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(limit_value=200, message='Slug is over 100 letters long!')])),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['-created_at'],
            },
        ),
    ]
