# Generated by Django 5.0.4 on 2024-10-09 12:49

import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_dislike'),
        ('posts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug', 'active', 'title'], name='posts_post_slug_d8ba2b_idx'),
        ),
        migrations.AddIndex(
            model_name='tags',
            index=models.Index(fields=['title'], name='posts_tags_title_d68d34_idx'),
        ),
    ]
