# Generated by Django 5.0.4 on 2024-10-10 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_managers_post_posts_post_slug_d8ba2b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(limit_value=100, message='Slug is over 100 letters long!')], verbose_name='Title'),
        ),
    ]
