# Generated by Django 5.0.4 on 2025-08-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_is_active_tags_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
