# Generated by Django 5.0.4 on 2025-08-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_post_deleted_at_tags_deleted_at"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="post",
            managers=[],
        ),
    ]
