# Generated by Django 5.0.2 on 2024-03-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='featured_img',
            field=models.ImageField(default='profiles/profile_default.jpg', upload_to='profiles/', verbose_name='A profile image'),
        ),
    ]
