# Generated by Django 5.0.4 on 2024-10-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_profile_featured_img'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['username', 'email'], name='users_profi_usernam_ef9a8b_idx'),
        ),
    ]
