# Generated by Django 5.0.4 on 2025-08-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_users_profi_usernam_ef9a8b_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='Male', max_length=40, null=True, verbose_name='Gender'),
        ),
    ]
