# Generated by Django 5.0.4 on 2025-07-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='disabled',
        ),
    ]
