# Generated by Django 5.0.4 on 2025-08-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0008_comment_deleted_at"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="comment",
            managers=[],
        ),
    ]
