# Generated by Django 5.0.4 on 2025-07-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='dislike',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='like',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
