# Generated by Django 5.0.4 on 2025-08-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0004_dislike_is_active_like_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dislike',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
