# Generated by Django 5.0.4 on 2025-07-24 19:39

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chat_is_active_message_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='chat',
            managers=[
                ('active_chats', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('active_messages', django.db.models.manager.Manager()),
            ],
        ),
    ]
