# Generated by Django 5.0.4 on 2025-08-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_chat_managers_alter_message_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(blank=True, choices=[('sent', 'Sent'), ('unsent', 'Unsent'), ('read', 'Read'), ('unread', 'Unread'), ('edited', 'Edited'), ('deleted', 'Deleted')], default='sent', max_length=10, null=True, verbose_name='Status'),
        ),
    ]
