# Generated by Django 5.0.4 on 2025-08-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_alter_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
