# Generated by Django 5.0.4 on 2025-08-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0006_chat_deleted_at_message_deleted_at"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="chat",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="message",
            managers=[],
        ),
    ]
