# Generated by Django 5.0.4 on 2025-07-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollowing',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
