# Generated by Django 5.0.4 on 2025-08-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0002_userfollowing_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollowing',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
